# Generated by Django 5.0.2 on 2024-02-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('add_custom_user_permission', 'Can add custom user permission'), ('change_custom_user_permission', 'Can change custom user permission'), ('delete_custom_user_permission', 'Can delete custom user permission')]},
        ),
    ]
